[Partition]
Type=linux-generic
Label=%M-images
Format=erofs
Compression=lz4
CopyFiles=/:/
ExcludeFiles=/boot
ExcludeFiles=/efi
ExcludeFiles=/usr
ExcludeFiles=/installer.raw
ExcludeFiles=/%M-%A.raw
Minimize=best
